# Generated by Django 4.0.6 on 2023-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0008_ad_seen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='vip_ad',
            field=models.BooleanField(default=False),
        ),
    ]
