# Generated by Django 4.0.6 on 2023-01-30 11:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0009_ad_vip_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_prev',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='post_imgs/'),
        ),
    ]
