# Generated by Django 4.0.6 on 2023-01-30 12:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0010_ad_image_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='post_imgs/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='post_imgs/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='post_imgs/'),
        ),
    ]
