# Generated by Django 4.0.6 on 2023-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_slider_mobile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='mobile_banner',
        ),
        migrations.AddField(
            model_name='minislider',
            name='mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_banner/'),
        ),
    ]
