# Generated by Django 4.0.6 on 2023-01-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0011_alter_ad_image_alter_ad_image_2_alter_ad_image_3'),
        ('banner', '0017_vipad_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipad',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='obyawleniya.categoryad'),
        ),
    ]
