# Generated by Django 4.0.6 on 2023-02-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_cource_price'),
        ('banner', '0019_slider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='minislider',
            name='link_mobile_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
